import React from 'react'
import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Footer'
import Sidebar from './Sidebar';

interface Props{
    children: any
}


const Layout = ({ children }: Props) => {
  return (
    <div className='layout overflow-x-hidden'>
        <Head>
        <title>Air man 23</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" type="image/png" href="/fireball.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com"  />
          <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet" />
      </Head>

      <header>
        <Navbar/>
      </header>

     <div className='flex'>
     <section>
      <Sidebar/>
     </section>

      <main>
        {children}
      </main>
     </div>
      <footer>
        <Footer/>
      </footer>
    </div>
  )
}

export default Layout