import React from 'react'
import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Footer'
import Sidebar from './Sidebar';

interface Props{
    children: any
}


const Layout = ({ children }: Props) => {
  return (
    <div className='layout'>
        <Head>
        <title>Air man 23</title>
        <meta name="description" content="Generated by create next app" />
     <link rel="shortcut icon" type="image/png" href="/fireball.png" />
      </Head>

      <header>
        <Navbar/>
      </header>

     <div className='flex'>
     <section>
      <Sidebar/>
     </section>

      <main className='md:px-28 flex justify-center overflow-x-hidden'>
        {children}
      </main>
     </div>
      <footer>
        <Footer/>
      </footer>
    </div>
  )
}

export default Layout