import Head from 'next/head'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Airman-23 | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


     <div className='banner'>
       <p className='banner-1'>New Products!</p>
       <div>
         <h1>Winter 2022</h1>
       </div>
     </div>
    
    </div>
  )
}
