import Head from 'next/head'
import Banner from '../components/Banner'
import Category from '../components/Category'
import { client } from '../lib/client'
import Product from '../components/Product'


interface Props {
  products: any
}

export default function Home({ products}: Props) {
  return (
    <div>
      <Head>
        <title>Airman-23 | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     {/**banner */}

     <Banner/>

     {/**categories */}
     <Category/>

     {/**latest feed */}
      
      <h2 className='ml-6 text-lg my-4 font-bold' >Latest :</h2>
     <div className='grid grid-cols-2 xl:grid-cols-3 mx-3'>
        { products?.map((product: any)=> <Product key={product._id} product={product} image={undefined} name={''} price={0} slug={''} />)}
       </div>
    </div>
  )
}

//server side props

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);
 
 
  return {
   props: { products }
  }
 
 }