import React from 'react'
import Head from 'next/head';
import {auth} from '../firebase'
import { useRouter } from 'next/router';
import { GoogleAuthProvider, signInWithRedirect, signInAnonymously } from 'firebase/auth'
import { useAuthState } from 'react-firebase-hooks/auth';
import Image from 'next/image';
import { motion} from 'framer-motion'


/**framer motion variants */
 
const sectionVariant = {
  hidden : { opacity: 0},
  show: { opacity: 1,
  transition: { duration: 1, delay: 0.2}
  }
}

const Login = () => {

  //set route

  const router = useRouter()
  const [user] = useAuthState(auth)

//onclick function to access with google

async function googleSignIn  () {

const provider = new GoogleAuthProvider()
signInWithRedirect(auth, provider)

}

/**sign in as guess */

async function signInAsGuess () {
  signInAnonymously(auth)
  router.push('/')
}

if(user) router.push({ pathname: '/' }) 

return (
<>
<Head>
        <title>Air man 23 | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#00708c" />

      </Head>
<div className="pt-10 flex justify-center"> 
    <Image 
        src="/blog-4.jpg"
        width={2000}
        height={2000}
        alt='login bg'
        priority
        className='w-screen h-screen object-cover'
    />

    <motion.div
      variants={sectionVariant}
      initial="hidden"
      whileInView="show"
      viewport={{ once: true }}
    className='absolute flex flex-col justify-center items-center place-items-center py-14 px-10 mx-[20%] md:w-[20vw] md:py-5 md:h-[50vh] login-card bg-white mt-36 rounded-md shadow-lg'>

<div className='flex justify-center'>
   <img src="/fireball.png" alt="logo" className='h-20' />
 </div>
 <h1 className='font-bold text-xl text-[#00708c] md:font-thin md:mt-6 logo-font md:text-xl arrival-text'>Airman-23</h1>

  <div className='flex-col flex my-8'>
  <button type='button' onClick={googleSignIn}  className='mt-10 cursor-pointer p-3  bg-[#00708c] hover:scale-110 transition duration-100 hover:bg-gray-900 rounded-xl text-white font-semibold text-center md:text-sm'>Login with Google</button>
  <button type='button' onClick={signInAsGuess}  className='mt-10 cursor-pointer p-2  bg-app hover:scale-110 transition duration-100 hover:bg-gray-200 rounded-xl text-[#00708c] border-2 border-[#00708c] text-center font-semibold md:text-sm'>Login as demo</button>

</div>
</motion.div>

</div>

  </>
  )
}


export default Login