import React from 'react'
import Link from 'next/link'
import Head from 'next/head'

const success = () => {
  return (
    <div className='bg-gray-200 w-screen md:flex md:justify-center h-screen md:pr-[20%] '>
        <Head>
        <title>Air man 23 | Success</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#00708c" />
        <link rel="shortcut icon" type="image/png" href="/fireball.png" />
      </Head>
       <div className='flex justify-center items-center '>
      <div className=' bg-white mt-[50%] md:mt-1 py-20 px-10 md:px-20 rounded-lg shadow-xl flex-col'>
      <h1 className='text-green-400  text-lg md:text-2xl'>Thank you for your purchase!</h1>

     <Link href={'/'} className='justify-center flex mt-10'>
         <button className='py-4 px-5 rounded-md shadow-md text-white bg-[#00708c]'>Continue Shopping</button>
     </Link>
      </div>
       </div>
    </div>
  )
}

export default success